name: auto-merge

on:
  workflow_dispatch:

env:
  ORG: "awslabs"
  TEAM: "aws-lambda-powertools-python"

jobs:
  maintainers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const query = `query($org: String!, $team: String!) { 
              organization(login:$org) {
                  team(slug:$team) {
                      members {
                          edges {
                              node {
                                  login
                              }
                          }
                      }
                  }
              }
            }`;

            const variables = {
              org: process.env.ORG,
              team: process.env.TEAM
            };

            const result = await github.graphql(query, variables);
            console.log(result);
            core.exportVariable('MAINTAINERS', result);
      - name: List maintainers
        run: echo $MAINTAINERS
