name: Record PR details

on:
  pull_request:
    types: [opened, edited, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Extract PR details"
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('.github/scripts/export_pr_details.js')
            script({github, context, core})
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr.txt
