# Maintenance: Verify why we're having permissions issues even with write scope, then re-enable it.
# logs: https://github.com/awslabs/aws-lambda-powertools-python/runs/7030238348?check_suite_focus=true

on:
  workflow_run:
    workflows: ["Record PR number"]
    types:
      - completed

env:
  RELEASE_LABEL: "pending-release"
  MAINTAINERS_TEAM: "@awslabs/aws-lambda-powertools-python"

jobs:
  release_label_on_merge:
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    # if: github.event.pull_request.merged == true && github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Label PR related issue for release"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/scripts/label_related_issue.js')
            await script({github, context, core})
