name: Label linked PR on merge
on:
  pull_request:
    types: [closed]

jobs:
  labelLinkedPrIssues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_linked_issues
        with:
          query: |
            query linkedIssues($url:String!) {
              resource(url:$url) {
                ... on PullRequest {
                  closingIssuesReferences(first: 10) {
                    nodes {
                      number
                    }
                  }
                }
              }
            }
          url: ${{ github.event.pull_request.url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/github-script@v6
        with:
          script: |
            const query = `query linkedIssues($url:URI!) {
              resource(url:$url) {
                ... on PullRequest {
                  closingIssuesReferences(first: 10) {
                    nodes {
                      number
                    }
                  }
                }
              }
            }`;
            const variables = {
              url: ${{ github.event.pull_request.url }},
            }
            const result = await github.graphql(query, variables)
            console.log(result)
      - name: 'Log object'
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            console.log(context.job)
      - run: "echo 'output: ${{ steps.get_linked_issues.outputs }}'"
      - run: "echo 'linked issues: ${{ steps.get_linked_issues.outputs.data }}'"
