name: Publish to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version_to_publish:
        description: "Version to be released in PyPi, Docs, and Lambda Layer, e.g. v1.26.4"
        default: v1.26.4
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name || inputs.version_to_publish }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set release notes tag
        run: |
          echo "RELEASE_VERSION: ${RELEASE_VERSION}"
          echo "RELEASE_TAG_VERSION=${RELEASE_VERSION:1}" >> $GITHUB_ENV
      - name: Output release tag version
        run: |
          echo "RELEASE_TAG_VERSION: ${RELEASE_TAG_VERSION}"
      - name: Rebuild changelog
        uses: ./.github/workflows/reusable_publish_changelog.yml
