name: Kickoff action script

on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: issue number to list labels for
        required: true

jobs:
  playground:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: List labels
        uses: actions/github-script@v5
        env:
          PR_NUMBER: ${{ inputs.issue_number }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('.github/scripts/comment_on_large_pr.js')
            await script({github, context, core})
